Add 5 fields to the schema
cfpb/ckanext-cfpb-extrafields pull request #52
Opened 2017-03-27 12:59 UTC by ambal007

2017-10-27 21:40 UTC, tanderegg commented
@mattboehm This looks about right to me, could you take a look as well?  Thanks!

2017-10-30 15:20 UTC, mattboehm requested changes
I'll need to make a handful of changes to this and then try testing it out on staging.

2017-10-30 15:20 UTC, mattboehm commented on ckanext/cfpb_extrafields/plugin.py
> +            'pra:_notes' : [tk.get_validator('ignore_missing'),
We need to remove the extra colon from this line

2017-10-30 15:20 UTC, mattboehm commented on ckanext/cfpb_extrafields/plugin.py
> +                                                tk.get_converter('convert_to_extras'),],
Need to double check whether each of these 5 fields should have these 2 converters

2017-10-30 15:20 UTC, mattboehm commented on ckanext/cfpb_extrafields/plugin.py
> +            'pra:_notes' : [tk.get_validator('ignore_missing'),
extra colon

2017-10-30 15:20 UTC, mattboehm commented on ckanext/cfpb_extrafields/templates/package/snippets/additional_info.html
> +        {% if transfer_date %}
These probably need to be `pkgdict.transfer_date`

2017-10-30 15:20 UTC, mattboehm commented on ckanext/cfpb_extrafields/templates/package/snippets/package_metadata_fields.html
> +{{ form_custom.radio('transfer_date',
These should not be radio inputs

2017-10-30 15:20 UTC, mattboehm commented on ckanext/cfpb_extrafields/templates/package/snippets/package_metadata_fields.html
> +      "transfer_date": "Initial date where the data was brought into the Bureau",
s/where/when

2018-09-24 15:59 UTC, closed without merging